{% set name = "llama-cloud-services" %}
{% set version = "0.6.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_cloud_services-{{ version }}.tar.gz
  sha256: 926b4ec6ffd5368b4a03e21b855842b098eaf96b71fe4b8c11cf3009a1429030

build:
  noarch: python
  entry_points:
    - llama-parse = llama_cloud_services.parse.cli.main:parse
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - platformdirs >=4.3.7,<5.0.0
    - python >={{ python_min }}
    - llama-index-core >=0.12.0
    - llama-cloud ==0.1.19
    - pydantic >=2.8,!=2.10
    - click >=8.1.7,<9.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - eval-type-backport >=0.2.0,<0.3.0

test:
  imports:
    - llama_cloud_services
  commands:
    - pip check
    - llama-parse --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Tailored SDK clients for LlamaCloud services.
  home: https://docs.cloud.llamaindex.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
