{% set name = "llama-cloud-services" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_cloud_services-{{ version }}.tar.gz
  sha256: 4e2ea6f9e632df62da456cbeb9d00665d09886d1caf759241ffa73c7c47d57c8

build:
  noarch: python
  entry_points:
    - llama-parse = llama_cloud_services.parse.cli.main:parse
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - llama-index-core >=0.11.0
    - llama-cloud >=0.1.15,<0.2.0
    - pydantic !=2.10
    - click >=8.1.7,<9.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - eval-type-backport >=0.2.0,<0.3.0

test:
  imports:
    - llama_cloud_services
  commands:
    - pip check
    - llama-parse --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Tailored SDK clients for LlamaCloud services.
  home: https://docs.cloud.llamaindex.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
