schema_version: 1

context:
  name: llama-cloud-services
  version: "0.6.55"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/llama_cloud_services-${{ version }}.tar.gz
  sha256: 38249bc379cfb358e6aa06927dc1ab9fbb305f3f336da32549a84570d5c77469

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - llama-parse = llama_cloud_services.parse.cli.main:parse

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - tenacity >=8.5.0,<10.0
    - platformdirs >=4.3.7,<5.0.0
    - python >=${{ python_min }}
    - llama-index-core >=0.12.0
    - llama-cloud ==0.1.37
    - pydantic >=2.8,!=2.10
    - click >=8.1.7,<9.0.0
    - python-dotenv >=1.0.1,<2.0.0
    - eval-type-backport >=0.2.0,<0.3.0

tests:
  - python:
      imports:
        - llama_cloud_services
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - llama-parse --help

about:
  summary: Tailored SDK clients for LlamaCloud services.
  license: MIT
  license_file: LICENSE
  homepage: https://docs.cloud.llamaindex.ai

extra:
  recipe-maintainers:
    - jan-janssen
